import { UsersService } from './users.service';
import { RegisterRequest } from './dtos/RegisterRequest.dto';
import { Userprofile } from './dtos/userprofile';
export declare class UsersController {
    private usersService;
    constructor(usersService: UsersService);
    getUsers(): import(".prisma/client").Prisma.PrismaPromise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        email: string;
        firstname: string;
        lastname: string;
        address: string;
        birthday: string;
        degree: string;
        number: number;
        job: string;
        image: string;
        hash: string;
        hashedAt: string;
        hashedRt: string;
        roleId: string[];
        basicSalary: number;
        offDays: number;
        familySituation: number;
        childrenNumber: number;
        bankrib: string;
        numCnss: string;
        taskId: string[];
        projectIds: string[];
    }[]>;
    getUserPrivilegesByEmail(email: string): Promise<{
        email: string;
        firstname: string;
        lastname: string;
        authorities: string[];
    }>;
    assignRole(body: {
        userId: string;
        roleId: string;
    }): Promise<{
        success: boolean;
        message: string;
    }>;
    addUser(registerRequest: RegisterRequest): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        email: string;
        firstname: string;
        lastname: string;
        address: string;
        birthday: string;
        degree: string;
        number: number;
        job: string;
        image: string;
        hash: string;
        hashedAt: string;
        hashedRt: string;
        roleId: string[];
        basicSalary: number;
        offDays: number;
        familySituation: number;
        childrenNumber: number;
        bankrib: string;
        numCnss: string;
        taskId: string[];
        projectIds: string[];
    }>;
    getUserByEmail(email: string): Promise<Userprofile>;
    getUserById(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        email: string;
        firstname: string;
        lastname: string;
        address: string;
        birthday: string;
        degree: string;
        number: number;
        job: string;
        image: string;
        hash: string;
        hashedAt: string;
        hashedRt: string;
        roleId: string[];
        basicSalary: number;
        offDays: number;
        familySituation: number;
        childrenNumber: number;
        bankrib: string;
        numCnss: string;
        taskId: string[];
        projectIds: string[];
    }>;
    deteteUser(id: string): import(".prisma/client").Prisma.PrismaPromise<import(".prisma/client").Prisma.BatchPayload>;
    updateUser(userId: string, updateUserDto: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        email: string;
        firstname: string;
        lastname: string;
        address: string;
        birthday: string;
        degree: string;
        number: number;
        job: string;
        image: string;
        hash: string;
        hashedAt: string;
        hashedRt: string;
        roleId: string[];
        basicSalary: number;
        offDays: number;
        familySituation: number;
        childrenNumber: number;
        bankrib: string;
        numCnss: string;
        taskId: string[];
        projectIds: string[];
    }>;
}
